language: python
python:
  - "2.7"

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+(-\S*)?$/

sudo: false
cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio
  - platformio update

script:
  - platformio run

before_deploy:
  - for file in .pio/build/*/*.bin; do filename=$(basename ${file%/*}.bin); cp ${file} ${filename}; sha1sum ${filename} > ${filename}.sha1; done

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: ./*.bin*
  skip_cleanup: true
  on:
    repo: area3001/ArduinoMendeleev
    tags: true
